# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CK3vABs8FIGCJ-1wIMml_95TaeepUNPi
"""

import random
aleatorio = random.randint(1,10)
print(aleatorio)

import random
aleatorio = random.randrange(1,10)
print(aleatorio)

chute_aleatorio = random.randint(1,100)

if chute_aleatorio:
   print('acertei','chute_aleatorio')
else:
   print('errei')



chute_aleatorio = random.radint(1,10)
meu_chute <= aleatorio:

#crie um sistema de senhas aleatorias
#1 computador cria uma senha aleatoria
#digiatr a senha
#verificar se o usuario pode ver

senha_pc = random.ran(10000,20000)
minha_senha = int(input(':'))
if senha_pc == aleatorio:
    print ('acesso permitido')
    print ('pode ver!')
else:
    print ('acesso negado')